#Langeuage default app language.
#Should be empty or inside Avaliable list
Language="zh-cn"
#Avaliable avaliable language
#Each language should be a folder in system/messages folder
#All translated messages should be putted in [modulesname].toml file.
#Avaliable=["zh-cn","jp"]
Avaliable=["zh-cn"]